### ISSUE TITLE
Deploy script on Eclipse Foundation openshift

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/eclipsefdn-github-sync#14]
@mbarbero Will deploy this script on our openshift infrastructure. The plan is to run this script every  hour.

@autumnfound What is the best way to test this script without using a real access token?

**Comment by autumnfound** [comment]
Could you elaborate on "real access token"? If you mean one that isn't for the actual org, there is sample data currently hardcoded in until we're ready to go live. If we give @mbarbero access to our test repo, that's where our test data is set to point at. He could then create a token for the test sandbox and run with the test data.

We'll have to put in a PR to enable the real data as right now its just commented out. Theoretically, we should be able to run with "dryrun" enabled, but I'd want to just double check to make sure there's no leaking at all

**Comment by chrisguindon** [comment]
> Could you elaborate on "real access token"?

I am thinking that for testing purposes, @mbarbero will generate a bogus access token such as "1234" which we will update once we are ready to go live.

The script should fail right away but it will be enough to allow @mbarbero to setup the service on openshift.

After this initial setup, we will want to update the access token with one that as access to our test organization.

If that goes well, we will update the script to run with real data.

**Comment by autumnfound** [comment]
Before, the script wouldn't stop with a bad access token provided. I'll be adding functionality in a PR that checks that the current token has the `admin:org` permission set at least before starting. This isn't perfect, as someone without access to the organizations being written to with that scope will still receive issues. However, since we are the only ones running this project, it should be sufficient. 

@mbarbero in order to pass in the secret, you can add a `secret` file containing just the personal access token you wish to use to the root of the project, and run the docker script I've created. If you add no content to this file and run the docker script + check the logs, you should receive a message that no API token could be retrieved. If there is content in the secret file other than a valid personal access token, it will return saying that the application doesn't have a valid access token.

If you wish to be more careful, you can set the dry run environment variable to true (--env DRYRUN=true). This should stop any writes to GitHub.

**Comment by chrisguindon** [comment]
I think we are good for this issue!

Everything is setup in openshift! Thanks @mbarbero
