### ISSUE TITLE
Github sync tooling - transition to a microservice

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/eclipsefdn-github-sync#6]
Once an hour it should automatically check the list of committers and teams and make sure everything is correct.

It should also accept single specific requests to add or remove a committer from a team.

This should also run as a separate user from Webmaster(on github).

Data sources:

The Eclipse projects api should be used as a source of truth about projects and their repos.  The committers API should be the truth for github ids, with ldap as a possible backup

**Comment by chrisguindon** [comment]
I am recommending that we move from a PHP solution () to Python. 

I propose that we leverage PyGitHub library to access the GitHub API v3 and Github Enterprise API v3:
https://github.com/PyGithub/PyGithub

This library will enable us to manage GitHub resources such as repositories, user profiles, and organizations in a Python application.

**Comment by chrisguindon** [comment]
Basic requirements for version 1:

- #1 
- #2 
- #3 
- #4 
- #5

**Comment by mbarbero** [comment]
Why Python? Who in the team knows Python very well? 

Is your recommendation based on the appeal of PyGithub? There are similar libraries in all languages https://developer.github.com/v3/libraries/. 

In Java, we even have the Eclipse EGit project providing something very similar to PyGithub (see https://github.com/eclipse/egit-github/tree/master/org.eclipse.egit.github.core). List of supported services APIv3 https://github.com/eclipse/egit-github/tree/master/org.eclipse.egit.github.core/src/org/eclipse/egit/github/core/service

**Comment by chrisguindon** [comment]
> Why Python? Who in the team knows Python very well?

I believe that choosing python for this project will allow us to complete this task faster since it's an easier language to learn.

We already created a prototype and we are pretty happy with what we were able to achieve in a short amount of time.

>Is your recommendation based on the appeal of PyGithub? There are similar libraries in all languages https://developer.github.com/v3/libraries/. In Java, we even have the Eclipse EGit project providing something very similar to PyGithub (see https://github.com/eclipse/egit-github/tree/master/org.eclipse.egit.github.core). List of supported services APIv3 https://github.com/eclipse/egit-github/tree/master/org.eclipse.egit.github.core/src/org/eclipse/egit/github/core/service

We are building a sync script and I believe that a scripting language such as Python is a better choice over Java for this project.

Also, I prefer a library with documentation and examples:
https://pygithub.readthedocs.io/en/latest/

**Comment by mbarbero** [comment]
> > Why Python? Who in the team knows Python very well?
> 
> I believe that choosing python for this project will allow us to complete this task faster since it's an easier language to learn.

So the goal is to learn a new language? Better do that on a pet project.

Also, completing a task faster is only part of the equation. This code will eventually needs to be maintained. I don't believe it is wise to implement something in a language that no one in the team master. No one can assess that the code is actually using the best practices of the language and even say that it's correct. It may do what's expected but nobody can review the code and say "this part is dangerous because you use this construct... etc..."

> We already created a prototype and we are pretty happy with what we were able to achieve in a short amount of time.

Still, it does not tell us about how easy it will be to maintain this script or to evolve it. I can tell that on Java code, you can tell that on PHP code, but who can say that on Python code?

> > Is your recommendation based on the appeal of PyGithub? There are similar libraries in all languages https://developer.github.com/v3/libraries/. In Java, we even have the Eclipse EGit project providing something very similar to PyGithub (see https://github.com/eclipse/egit-github/tree/master/org.eclipse.egit.github.core). List of supported services APIv3 https://github.com/eclipse/egit-github/tree/master/org.eclipse.egit.github.core/src/org/eclipse/egit/github/core/service
> 
> We are building a sync script and I believe that a scripting language such as Python is a better choice over Java for this project.

So the argument is because Python is a "scripting" language? Please elaborate. 

> Also, I prefer a library with documentation and examples:
> https://pygithub.readthedocs.io/en/latest/

EGit Github integration has a pretty decent javadoc (it's not available online though, it's available from IDE or if one download it from [OSSRH](https://oss.sonatype.org/service/local/repositories/releases/content/org/eclipse/mylyn/github/org.eclipse.egit.github.core/2.1.5/org.eclipse.egit.github.core-2.1.5-javadoc.jar)


I would be all in for Python if PyGithub were the only library wrapping the GitHub REST API. But it seems that there is a very good library in a language the team knows about. IMO, it makes it an obvious choice.

**Comment by chrisguindon** [comment]
As discussed with you on Slack, the goal is definitely not to learn a new language. 

With this said, I wouldn't be doing my job correctly if I did not consider Java for this project. 

@autumnfound Could you implement a proof on concept by implementing the same functionality that you did for PR #7 in Java.

Once that done, we will discuss the pros and cons of both before moving forward with one or the other.

The most important thing for me is that we use a library for interacting with GitHub API and we implement a solution that we can easily maintain.

**Comment by autumnfound** [comment]
I've created 3 different PRs, one using Python, one using Java, and one using Node.js to fix the same issue (#1). Below are some notes on the experience developing using the three languages and toolkits, as well as some potential traps I see.

## Python

- Uses PyGitHub, a community maintained GitHub binding for Python. While this is still very active and under MIT license, interest and support may drop due to nature of community projects.
- Relatively straight forward language, with ~5 people skilled in scripting to the point of being able to support this project. 
- We have no existing architecture or processes for building, releasing, or maintaining Python.

## Java

- Uses EGit, which promotes internal toolsets and open source. As this is community maintained, this may mean that issues and new features aren't added for a period of time until someone needs it. As its an Eclipse Foundation project, we have easier access to communicating with maintainers and committers, along with joining the project if desired.
  - To this end, I encountered a missing feature in EGit where I cannot set a new team to visible but closed.
- Currently, only 2 members of team can comfortably develop in Java, which creates dependencies on Mikael or I to do any changes in this project. In my mind, this is worrying for sustainability and for responsive fixes to the project should something arise.
- Maven + Travis/Jenkins provides rich build environment support, along with previous experience on other projects.
- JVM's are resource heavy compared to scripting languages, and require more involved environments + development time due to nature of language (compiled vs runtime language).

## Node.js

- Uses official GitHub bindings (@octokit/rest). This would mean unless deprecated, this binding will be the most up to date of the three available.
- Somewhat higher barrier of entry than Python, but lower than Java. Currently I and the web team can directly support if needed.
- NPM + Travis provides rich environment support, along with previous experience on other projects in maintaining build environments.
- Quickest of three tested languages in development + testing. This has to do with incredibly mature official API, and nature of Node.js.

In my opinion Node.js is the best bet for this project, followed then by Python, then Java. Scripting languages are much more appropriate for the type of work than a more robust runtime (we don't need it). Node.js floats to the top to me for its official support, quick development, and existing build environments.

**Comment by mbarbero** [comment]
+1 for nodejs. Being an official toolkit (and seemingly high-quality) in a team-known language makes it an obvious choice.

Just a note about:

> JVM's are resource heavy compared to scripting languages, and require more involved environments + development time due to nature of language (compiled vs runtime language).

This is at best incorrect. Java "heaviness" is an old fallacy. Same for compiled vs interpreted. This is mostly polemical arguments / matter of tastes and we'd better stay off those when doing technical choices.

**Comment by chrisguindon** [comment]
The script had it first successful run today!

Thanks @autumnfound for your great work on this!
